feat: Allow explicit XamlDictionary initialization
Context: https://github.com/unoplatform/Uno.Gallery/pull/1233
Context: https://github.com/unoplatform/uno-private/issues/1696#issuecomment-3813491375

What do we want? To build and run Uno.Gallery with NativeAOT!
(See also: unoplatform/Uno.Gallery#1233)

We also want Uno.Gallery to run *properly*.

The problem: The "`<>` Show XAML" button doesn't work properly.

Use unoplatform/Uno.Gallery#1233 to build and run Uno.Gallery with
NativeAOT:

	dotnet publish -c Release -r osx-x64 -f net10.0-desktop -p:TargetFrameworkOverride=net10.0-desktop \
	  -bl Uno.Gallery/Uno.Gallery.csproj -p:UseSkiaRendering=true -p:SelfContained=true \
	  -p:SkiaPublishAot=true
	./Uno.Gallery/bin/Release/net10.0-desktop/osx-x64/publish/Uno.Gallery

Once the app has launched, select **UI components > AutoSuggestBox**
in the left-hand tree.  Then, in the right-hand panel, click the
"`<>` Show XAML" button.

Expected results: *Something is shown*.

Actual results: An empty box is shown.

As with most NativeAOT-related issues, this is due to Reflection:
`XamlDisplay.Init()` tries to lookup the `ShowMeTheXAML.XamlDictionary`
type from an `Assembly`.  By default, nothing is statically referencing
`XamlDictionary`, so it isn't accessible via Reflection, so this
attempted lookup (silently) fails.

This aspect can be worked around in Uno.Gallery via
[`[DynamicDependency]`][0], e.g.

	diff --git a/Uno.Gallery/App.xaml.cs b/Uno.Gallery/App.xaml.cs
	index 51ae161a..45b16dfd 100644
	--- a/Uno.Gallery/App.xaml.cs
	+++ b/Uno.Gallery/App.xaml.cs
	@@ -78,6 +78,7 @@ namespace Uno.Gallery
	                        }
	                }

	+               [System.Diagnostics.CodeAnalysis.DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(ShowMeTheXAML.XamlDictionary))]
	                private void OnLaunchedOrActivated()
	                {
	                        MainWindow = new Window();

The problem is that once `XamlDisplay.Init()` finds `XamlDictionary`,
it then attempts to invoke its static constructor:

	//Invoke the static constructor
	global::System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor(xamlDictionary.TypeHandle);

*This* fails, hard:

	System.NotSupportedException: 'ShowMeTheXAML.XamlDictionary' is missing native code or metadata. This can happen for code that is not compatible with trimming or AOT. Inspect and fix trimming and AOT related warnings that were generated when the app was published. For more information see https://aka.ms/nativeaot-compatibility
	   at System.Reflection.Runtime.TypeInfos.RuntimeTypeInfo.get_TypeHandle() + 0x95
	   at ShowMeTheXAML.XamlDisplay.<Init>g__LoadFromAssembly|7_0(Assembly) + 0x4d
	   at ShowMeTheXAML.XamlDisplay.Init(Assembly[]) + 0x47
	   at Uno.Gallery.App..ctor() + 0x99
	   at Uno.Gallery.Program.<>c.<Main>b__0_0() + 0x18
	   at Uno.UI.Runtime.Skia.MacOS.MacSkiaHost.<StartApp>g__CreateApp|18_0(ApplicationInitializationCallbackParams _) + 0x21
	   at Microsoft.UI.Xaml.Application.StartPartial(ApplicationInitializationCallback) + 0x70
	   at Uno.UI.Runtime.Skia.MacOS.MacSkiaHost.StartApp() + 0xbc

Address this by removing the *need* for Reflection: update the
`XamlDictionary` templates to contain a static `Init()` method:

	partial class XamlDictionary
	{
	    public static void Init()
	    {
	    }
	}

This allows Uno.Gallery to *explicitly* call `XamlDictionary.Init()`,
which *implicitly* invokes the `XamlDictionary` static constructor,
avoiding the need for Reflection *entirely*.

This in turn allows the "`<>` Show XAML" button to work properly.

Additionally, make the `XamlDictionary` declaration `partial`, so
that if future "workarounds" such as `Init()` are needed, a new
`Uno.ShowMeTheXAML.MSBuild` NuGet package isn't required.

[0]: https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.dynamicdependencyattribute?view=net-9.0