build: Build with.NET 10, Target .NET 9
CI no longer builds with .NET 6.  The **Install .NET WOrkloads** step
"fails" (green but has errors) with:

	» Attempting to fix: .NET SDK - Workloads (6.0.400-rtm.22364.21)
	System.IO.FileNotFoundException: Could not find file 'C:\Program Files\dotnet\sdk-manifests\10.0.100\microsoft.net.sdk.android\WorkloadManifest.json'.
	…
	Checkup had Error status: dotnetworkloads-6.0.400-rtm.22364.21

	dotnetworkloads-6.0.400-rtm.22364.21:
	! There were one or more problems detected.
	Please review the errors and correct them and run uno-check again.
	Has Errors? True

The **MSBuild** step fails with:

	  C:\Program Files\dotnet\sdk\10.0.102\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.ImportWorkloads.targets(38,5): error NETSDK1147: To build this project, the following workloads must be installed: ios wasm-tools-net6 [D:\a\1\s\ShowMeTheXAML\Uno.ShowMeTheXAML.csproj::TargetFramework=net6.0-ios]

CI last successfully built on 2023-Aug-9, which is quite some time ago.

Update CI to use .NET 10 and target .NET 9.